Application:
  debug: true
  port: 8081
Database:
  host: localhost
  port: 3306
  name: finechat
  user: root
  password: 1234
RabbitMQ:
  host: 192.168.0.11
  port: 5672
  user: cfuser
  password: 1234
