version: '3.7'

services:
  db:
    image: mariadb:10.6.4
    networks:
      - db-net
    configs:
      - source: db_schema
        target: /docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: my_super_secret_password

  rabbitmq:
    image: rabbitmq:3.9.12-management
    networks:
      - broker-net
    environment:
      RABBITMQ_DEFAULT_USER: fcuser
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_ERLANG_COOKIE: 1234

  app:
    image: finechatapp:latest
    ports:
      - 8081:8080
    networks:
      - broker-net
      - db-net
    configs:
      - source: configuration
        target: /finechat/configuration.yml

  bot:
    image: finechatbot:latest
    networks:
      - broker-net
    configs:
      - source: configuration
        target: /finechatbot/configuration.yml

configs:
  configuration:
    file: ./configuration.yml
  db_schema:
    file: ./finechatapp/finechat_schema.sql

networks:
  db-net:
  broker-net: